import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import * as fs from 'fs';
import * as path from 'path';

const docsDir = path.resolve(__dirname, 'docs');
const sections = fs
  .readdirSync(docsDir)
  .filter((name) => fs.statSync(path.join(docsDir, name)).isDirectory())
  .sort();

const sidebars: SidebarsConfig = {};

for (const section of sections) {
  sidebars[`${section}Sidebar`] = [
    {
      type: 'autogenerated',
      dirName: section,
    },
  ];
}

export default sidebars;
